apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: simplerollouttraits.extend.oam.dev
  annotations:
    rudrx.oam.dev/template: simplerollouttraits.extend.oam.dev-template
    short: SimpleRollout
spec:
  revisionEnabled: true
  appliesToWorkloads:
    - core.oam.dev/v1alpha2.ContainerizedWorkload
    - deployments.apps
  definitionRef:
    name: simplerollouttraits.extend.oam.dev
