apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: backend
  annotations:
    definition.oam.dev/apiVersion: "standard.oam.dev/v1alpha1"
    definition.oam.dev/kind: "Containerized"
spec:
  definitionRef:
    name: containerizeds.standard.oam.dev
  childResourceKinds:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Service
  extension:
    template: |
      #Template: {
      	apiVersion: "standard.oam.dev/v1alpha1"
      	kind:       "Containerized"
      	metadata:
      		name: backend.name
      	spec: {
      		containers: [{
      			image: backend.image
      			name:  backend.name
      		}]
      	}
      }

      backend: {
      	name: string
      	// +usage=specify app image
      	// +short=i
      	image: string
      }
