apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: backend
  annotations:
    definition.oam.dev/apiVersion: "standard.oam.dev/v1alpha1"
    definition.oam.dev/kind: "PodSpecWorkload"
spec:
  definitionRef:
    name: podspecworkload.standard.oam.dev
  childResourceKinds:
    - apiVersion: apps/v1
      kind: Deployment
  extension:
    template: |
      data: {
        apiVersion: "standard.oam.dev/v1alpha1"
        kind:       "PodSpecWorkload"
        metadata:
          name: parameter.name
        spec: {
          replicas: 1
            podSpec: {
              containers: [{
                 image: parameter.image
                   name:  parameter.name
               }]
            }
        }
      }
      #backend: {
        name: string
          // +usage=specify app image
          // +short=i
        image: string
      }
      parameter: #backend

