apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-config
  namespace: {{ .Release.Namespace }}
data:
  servicemonitors.monitoring.coreos.com: |
    {
      "repo": "prometheus-community",
      "urL": "https://prometheus-community.github.io/helm-charts",
      "name": "kube-prometheus-stack",
      "namespace": "monitoring",
      "version": "9.4.4"
    }
  ingresses.networking.k8s.io: |
    {
      "repo": "ingress-nginx",
      "urL": "https://kubernetes.github.io/ingress-nginx",
      "name": "ingress-nginx",
      "namespace": "vela-system",
      "version": "3.7.1"
    }
  flagger.app: |
    {
      "repo": "flagger",
      "urL": "https://flagger.app",
      "name": "flagger",
      "namespace": "vela-system",
      "version": "1.2.0"
    }