apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metric
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: MetricsTrait
    definition.oam.dev/description: "Add metric monitoring for workload"
spec:
  appliesToWorkloads:
    - webservice
    - backend
    - task
    - containerizedworkloads.core.oam.dev
    - clonesetworkloads.apps.kruise.io
    - deployments.apps
    - statefulsets.apps
  definitionRef:
    name: metricstraits.standard.oam.dev
  workloadRefPath: spec.workloadRef
  extension:
    template: |-
      output: {
      	apiVersion: "standard.oam.dev/v1alpha1"
      	kind:       "MetricsTrait"
      	spec: {
      		scrapeService: parameter
      	}
      }
      parameter: {
      	// +usage=format of the metrics, default as prometheus
      	// +short=f
      	format: *"prometheus" | string
      	// +usage= the metric path of the service
      	path:    *"/metrics" | string
      	scheme:  *"http" | string
      	enabled: *true | bool
      	// +usage= the port for metrics, will discovery automatically by default
      	port: *0 | >=1024 & <=65535 & int
      	// +usage= the label selector for the pods, will discovery automatically by default
      	selector?: [string]: string
      }
      
