replicas: 1

deploymentStrategy: RollingUpdate

image:
  repository: crossplane/crossplane
  tag: v0.14.0-rc.18.g99c02be
  pullPolicy: Always

args: {}

provider:
  packages: []

imagePullSecrets:
- dockerhub

rbacManager:
  deploy: true
  managementPolicy: All
  args: {}

priorityClassName: ""

resourcesCrossplane:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

packageCache:
  medium: ""
  sizeLimit: 5Mi
  pvc: ""

resourcesRBACManager:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

alpha:
  oam:
    enabled: false
