apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: appconfig-scaler
spec:
  components:
    - componentName: component-scaler
      traits:
        - trait:
            apiVersion: standard.oam.dev/v1alpha1
            kind: Autoscaler
            metadata:
              name: trait-scaler
            spec:
              minReplicas: 1
              maxReplicas: 10
              triggers:
                - name: weekday-cron
                  enabled: true
                  type: cron
                  condition:
                    startAt: "22:47"
                    duration: 1m
                    days: "Monday, Tuesday"
                    replicas: "3"
                    timezone: Asia/Shanghai
                - type: cpu
                  name: my-cpu-con
                  enabled: true
                  condition:
                    type: Utilization
                    value: "70"