apiVersion: admin.oam.dev/v1alpha2
kind: Template
metadata:
  annotation:
    version: 0.0.1
  name: manualscalertrait.core.oam.dev-template
spec:
  object:
    apiVersion: core.oam.dev/v1alpha2
    kind: ManualScalerTrait
    spec:
      replicaCount: 2
  parameters:
    - name: replicaCount
      required: true
      type: int
      default: "5"
      fieldPaths:
        - "spec.replicaCount"
