version: "1.0-alpha.1"
name: myapp

services:
  data-api:
    type: backendworker
    image: artursouza/rudr-data-api:0.50
    name: data-api
    port: 3009
    env:
      - name: DATABASE_NAME
        value: postgres
      - name: DATABASE_DRIVER
        value: postgresql
      - name: DATABASE_HOSTNAME
        _useSecret: true
        secretKeyRef: 
          name: db-conn
          key: endpoint
      - name: DATABASE_USER 
        _useSecret: true
        secretKeyRef: 
          name: db-conn
          key: username
      - name: DATABASE_PASSWORD 
        _useSecret: true
        secretKeyRef: 
          name: db-conn
          key: password
      - name: DATABASE_PORT
        _useSecret: true
        secretKeyRef: 
          name: db-conn
          key: port

  flight-api:
    type: backendworker
    image: sonofjorel/rudr-flights-api:0.49
    name: flights-api
    port: 3003
    env:
      - name: data-uri 
        value: http://data-api.default.svc.cluster.local:3009/

  quake-api:
    type: backendworker
    image: sonofjorel/rudr-quake-api:0.49
    name: quake-api
    port: 3012
    env:
      - name: data-uri 
        value: http://data-api.default.svc.cluster.local:3009/

  weather-api:
    type: backendworker
    image: sonofjorel/rudr-weather-api:0.49
    name: weather-api
    port: 3012
    env:
      - name: data-uri 
        value: http://data-api.default.svc.cluster.local:3009/

  web-ui:
    type: webui
    image: sonofjorel/rudr-web-ui:0.49
    name: web-ui
    port: 8080
    env:
      - name: flights-uri 
        value: http://flights-api.default.svc.cluster.local:3003/
      - name: weather-uri
        value: http://weather-api.default.svc.cluster.local:3015/
      - name: quakes-uri
        value: http://quakes-api.default.svc.cluster.local:3012/

  


  
