apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: route
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: Route
    definition.oam.dev/description: "Add a route for workload"
spec:
  appliesToWorkloads:
    - core.oam.dev/v1alpha2.ContainerizedWorkload
    - standard.oam.dev/v1alpha1.PodSpecWorkload
    - deployments.apps
    - webservice
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: routes.standard.oam.dev
  extension:
    template: |
      output: {
        apiVersion: "standard.oam.dev/v1alpha1"
        kind:       "Route"
        spec: {
          host: parameter.domain
          tls: {
            issuerName: parameter.issuer
          }
        }
      }
      #route: {
        domain: *"" | string
        issuer: *"" | string
      }
      parameter: #route

