apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: autoscale
  annotations:
    definition.oam.dev/description: "Automatically scale workloads"
spec:
  appliesToWorkloads:
    - webservice
    - backend
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: autoscalers.standard.oam.dev
  extension:
    template: |
