apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Scale replica for workload"
  name: scaler
spec:
  appliesToWorkloads:
    - webservice
    - containerizedworkloads.core.oam.dev
    - deployments.apps
  definitionRef:
    name: manualscalertraits.core.oam.dev
  workloadRefPath: spec.workloadRef
  extension:
    template: |-
