version: "1.0-alpha.1"
name: lab3

services:
  database:
    type: rds
    name: alibabaRds

  data-api:
    type: backend
    image: artursouza/rudr-data-api:0.50
    name: data-api
    port: 3009
    env:
      - name: DATABASE_NAME
        value: postgres
      - name: DATABASE_DRIVER
        value: postgresql
      - name: DATABASE_HOSTNAME
        _useSecret: true
        secretKeyRef: 
          name: db-conn
          key: endpoint
      - name: DATABASE_USER 
        _useSecret: true
        secretKeyRef: 
          name: db-conn
          key: username
      - name: DATABASE_PASSWORD 
        _useSecret: true
        secretKeyRef: 
          name: db-conn
          key: password
      - name: DATABASE_PORT
        _useSecret: true
        secretKeyRef: 
          name: db-conn
          key: port

  flights-api:
    type: backend
    image: sonofjorel/rudr-flights-api:0.49
    name: flights-api
    port: 3003
    env:
      - name: DATA_SERVICE_URI 
        value: http://data-api.default.svc.cluster.local:3009/

  quakes-api:
    type: backend
    image: sonofjorel/rudr-quakes-api:0.49
    name: quakes-api
    port: 3012
    env:
      - name: DATA_SERVICE_URI 
        value: http://data-api.default.svc.cluster.local:3009/

  weather-api:
    type: backend
    image: sonofjorel/rudr-weather-api:0.49
    name: weather-api
    port: 3015
    env:
      - name: DATA_SERVICE_URI 
        value: http://data-api.default.svc.cluster.local:3009/

  web-ui:
    type: webservice
    image: sonofjorel/rudr-web-ui:0.49
    name: web-ui
    port: 8080
    env:
      - name: FLIGHTS_API_ROOT
        value: http://flights-api.default.svc.cluster.local:3003/
      - name: WEATHER_API_ROOT
        value: http://weather-api.default.svc.cluster.local:3015/
      - name: QUAKES_API_ROOT
        value: http://quakes-api.default.svc.cluster.local:3012/


  
