version: "1.0-alpha.1"
name: testapp

services:
  express-server:
    # this image will be used in both build and deploy steps
    image: oamdev/testapp:v1

    build:
      # Here more runtime specific build templates will be supported, like NodeJS, Go, Python, Ruby.
      docker:
        file: Dockerfile
        context: .

      # Uncomment the following to push to local kind cluster
      push:
        local: kind

    # type: webservice (default) | worker | task

    port: 8080

    env:
      - FOO=bar
      - FOO2=sec:my-secret # map the key same as the env name (`FOO2`) from my-secret to env var
      - FOO3=sec:my-secret:key # map specific key from my-secret to env var
      - sec:my-secret # map all KV pairs from my-secret to env var

    files: # Mount secret as a file
      - /mnt/path=sec:my-secret

    scaler:
      replica: 1

    route:
      domain: example.com

    # metrics:
    #   format: "prometheus"
    #   port: 8080
    #   path: "/metrics"
    #   scheme:  "http"
    #   enabled: true